version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: task-db
    env_file:
      - ./.env
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - task_manager

  backend:
    build: ./backend
    env_file:
      - ./.env
    container_name: task-backend
    depends_on:
      - db
    ports:
      - "2500:5000"
    networks:
      - task_manager

  frontend:
    build: ./frontend
    container_name: task-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - task_manager

  nginx:
    image: nginx:alpine
    container_name: task-nginx
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - "80:80"
    networks:
      - task_manager

networks:
  task_manager:
    driver: bridge